combining several PRs with my own twist

diff --git a/docker-entrypoint b/docker-entrypoint
--- a/docker-entrypoint
+++ b/docker-entrypoint
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 set -e
 # shellcheck disable=2039
@@ -8,8 +8,13 @@ DOCKER_SOCK=${DOCKER_SOCK:-/var/run/docker.sock}
 UNIX_SOCK=""
 CURL_TIMEOUT=${CURL_TIMEOUT:-30}
 WEBHOOK_URL=${WEBHOOK_URL:-""}
-WEBHOOK_JSON_KEY=${WEBHOOK_JSON_KEY:-"text"}
-APPRISE_URL=${APPRISE_URL:-""}
+
+PUBLIC_IP=$(curl -s https://api.ipify.org)
+
+if [ -z "$PUBLIC_HOSTNAME" ]; then
+  PUBLIC_HOSTNAME=$PUBLIC_IP
+fi
+
 
 # only use unix domain socket if no TCP endpoint is defined
 case "${DOCKER_SOCK}" in
@@ -29,6 +34,7 @@ AUTOHEAL_CONTAINER_LABEL=${AUTOHEAL_CONTAINER_LABEL:-autoheal}
 AUTOHEAL_START_PERIOD=${AUTOHEAL_START_PERIOD:-0}
 AUTOHEAL_INTERVAL=${AUTOHEAL_INTERVAL:-5}
 AUTOHEAL_DEFAULT_STOP_TIMEOUT=${AUTOHEAL_DEFAULT_STOP_TIMEOUT:-10}
+AUTOHEAL_RETRIES=${AUTOHEAL_RETRIES:-5}
 
 docker_curl() {
   curl --max-time "${CURL_TIMEOUT}" --no-buffer -s \
@@ -52,6 +58,7 @@ get_container_info() {
   url="${HTTP_ENDPOINT}/containers/json?filters=\{\"health\":\[\"unhealthy\"\]${label_filter}\}"
   docker_curl "$url"
 }
+
 
 # shellcheck disable=2039
 restart_container() {
@@ -127,38 +134,69 @@ then
     sleep "$AUTOHEAL_START_PERIOD" &
     wait $!
   fi
-
+  
+  declare -A SICK_CONTAINERS
+  
   while true
   do
     STOP_TIMEOUT=".Labels[\"autoheal.stop.timeout\"] // $AUTOHEAL_DEFAULT_STOP_TIMEOUT"
-    get_container_info | \
-      jq -r ".[] | select(.Labels[\"autoheal\"] != \"False\") | foreach . as \$CONTAINER([];[]; \$CONTAINER | .Id, .Names[0], .State, ${STOP_TIMEOUT})" | \
+    shopt -s lastpipe; set +m; get_container_info | \
+      jq -r "foreach .[] as \$CONTAINER([];[]; \$CONTAINER | .Id, .Names[0], .State, ${STOP_TIMEOUT})" | \
       while read -r CONTAINER_ID && read -r CONTAINER_NAME && read -r CONTAINER_STATE && read -r TIMEOUT
     do
       # shellcheck disable=2039
       CONTAINER_SHORT_ID=${CONTAINER_ID:0:12}
       DATE=$(date +%d-%m-%Y" "%H:%M:%S)
-
+      DATE_SCRIPT=$(date '+%Y-%m-%d %H:%M:%S')
       if [ "$CONTAINER_NAME" = "null" ]
       then
         echo "$DATE Container name of (${CONTAINER_SHORT_ID}) is null, which implies container does not exist - don't restart" >&2
       elif [ "$CONTAINER_STATE" = "restarting" ]
       then
-        echo "$DATE Container $CONTAINER_NAME (${CONTAINER_SHORT_ID}) found to be restarting - don't restart"
+        echo "$DATE Container ${CONTAINER_NAME:1} (${CONTAINER_SHORT_ID}) found to be restarting - don't restart" >&2
       else
-        echo "$DATE Container $CONTAINER_NAME (${CONTAINER_SHORT_ID}) found to be unhealthy - Restarting container now with ${TIMEOUT}s timeout"
-        if ! restart_container "$CONTAINER_ID" "$TIMEOUT"
-        then
-          echo "$DATE Restarting container $CONTAINER_SHORT_ID failed" >&2
-          notify_webhook "Container ${CONTAINER_NAME:1} (${CONTAINER_SHORT_ID}) found to be unhealthy. Failed to restart the container!" &
+        if [ ${SICK_CONTAINERS[$CONTAINER_ID]+_} ]; then
+          echo "$DATE Container ${CONTAINER_NAME:1} (${CONTAINER_SHORT_ID}) already in a queue" >&2
         else
-          notify_webhook "Container ${CONTAINER_NAME:1} (${CONTAINER_SHORT_ID}) found to be unhealthy. Successfully restarted the container!" &
+          echo "$DATE Container ${CONTAINER_NAME:1} (${CONTAINER_SHORT_ID}) found to be unhealthy - adding to queue" >&2
+          SICK_CONTAINERS[$CONTAINER_ID]="CONTAINER_ID=\"$CONTAINER_ID\" CONTAINER_SHORT_ID=\"$CONTAINER_SHORT_ID\" CONTAINER_NAME=\"$CONTAINER_NAME\" CONTAINER_STATE=\"$CONTAINER_STATE\" TIMEOUT=\"$TIMEOUT\" RETRY=0"
         fi
-        notify_post_restart_script "$CONTAINER_NAME" "$CONTAINER_SHORT_ID" "$CONTAINER_STATE" "$TIMEOUT" &
       fi
     done
-    sleep "$AUTOHEAL_INTERVAL" &
-    wait $!
+
+    declare -A SICK_CONTAINERS_NEW
+
+    for SICK_CONTAINER in "${SICK_CONTAINERS[@]}"; do
+      eval "$SICK_CONTAINER"
+
+      if ! restart_container "$CONTAINER_ID" "$TIMEOUT"
+      then
+        echo "$DATE Restarting container $CONTAINER_SHORT_ID failed" >&2
+        notify_webhook "Container ${CONTAINER_NAME:1} (${CONTAINER_SHORT_ID}) on ${PUBLIC_HOSTNAME} found to be unhealthy. Failed to restart the container!" &
+
+        RETRY_NEW=$((RETRY+1))
+        if [ $RETRY_NEW -lt $AUTOHEAL_RETRIES ]; then
+          SICK_CONTAINER_NEW="${SICK_CONTAINER/RETRY=$RETRY/RETRY=$RETRY_NEW}"
+          SICK_CONTAINERS_NEW[$CONTAINER_ID]="$SICK_CONTAINER_NEW"
+        else
+          echo "$DATE All attempts to restart the container $CONTAINER_SHORT_ID have failed" >&2
+        fi
+      else
+        echo "$DATE Container ${CONTAINER_NAME:1} (${CONTAINER_SHORT_ID}) - successfully restarted the container" >&2
+        notify_webhook "Container ${CONTAINER_NAME:1} (${CONTAINER_SHORT_ID})  on ${PUBLIC_HOSTNAME} found to be unhealthy. Successfully restarted the container!" &
+      fi
+      notify_post_restart_script "$DATE_SCRIPT" ${CONTAINER_NAME:1} "$CONTAINER_SHORT_ID" "$CONTAINER_STATE" "$TIMEOUT" &
+    done
+
+    unset SICK_CONTAINERS
+    declare -A SICK_CONTAINERS
+
+    for idx in "${!SICK_CONTAINERS_NEW[@]}"; do
+      SICK_CONTAINERS[$idx]="${SICK_CONTAINERS_NEW[$idx]}"
+    done
+    unset SICK_CONTAINERS_NEW
+
+    sleep "$AUTOHEAL_INTERVAL"
   done
 
 else
